version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/*"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 0"
  - dependency-name: framer-motion
    versions:
    - 3.1.1
    - 4.0.3
    - 4.1.2
    - 4.1.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: dtslint
    versions:
    - 4.0.8
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.9
  - dependency-name: karma-webpack
    versions:
    - 5.0.0
  - dependency-name: webpack
    versions:
    - 5.12.3
    - 5.21.2
    - 5.23.0
    - 5.28.0
  - dependency-name: "@popperjs/core"
    versions:
    - 2.6.0
    - 2.9.1
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: marked
    versions:
    - 2.0.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: "@types/yargs"
    versions:
    - 15.0.12
  - dependency-name: babel-plugin-module-resolver
    versions:
    - 4.1.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.14
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.6
  - dependency-name: yargs
    versions:
    - 16.2.0
